set shiftwidth=2
set tabstop=2
set softtabstop=2
set scrolloff=6
set showtabline=2
set whichwrap=bs<>[]hl
set completeopt="menuone,noselect"
set number
set relativenumber
set ignorecase
set smartcase
set showmatch
set hlsearch
set incsearch
set wildmenu
set noswapfile
set ruler
set expandtab
set smartindent
set breakindent

let g:netrw_dirhistmax=0

nmap [<space> O<Esc>j
nmap ]<space> o<Esc>k

nmap <C-k> 10k
nmap <C-j> 10j
nmap <C-Up> 10k
nmap <C-Down> 10j

imap <C-q> <Esc>
imap <C-z> <Esc>u
imap <C-r> <Esc><C-r>
imap <C-s> <Esc>:w<cr>

map <leader>e :Explore<cr>
map <C-q> <Esc>
map <C-z> <Esc>u
map <C-s> <Esc>:w<cr>

map <Tab>a :buffers<cr>
map <Tab><Left> :bprevious<cr>
map <Tab><Right> :bnext<cr>
map <Tab>h :bprevious<cr>
map <Tab>l :bnext<cr>
map <Tab>c :bdelete<cr>
map <Tab>x :bdelete!<cr>

