# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.

COMMON_FLAGS="-O2 -pipe"

CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="-C target-cpu=native"

USE="acl alsa bzip2 cet cjk cxx crypt dbus elogind gdbm iconv ipv6 libtirpc mime networkmanager ncurses nls opengl openmp pam pipewire readline seccomp ssl test-rust unicode vulkan xattr zlib wayland -X -systemd -kde -plasma -gnome"

ACCEPT_LICENSE="-* @FREE @BINARY-REDISTRIBUTABLE"
FEATURES="${FEATURES} getbinpkg binpkg-request-signature"
MAKEOPTS="-j8 -l10"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8
GRUB_PLATFORMS="efi-64"
