local colors = {
	fg = "#c8d3f5",
	bg0 = "#0f101a",
	bg1 = "#1a1c2b",
	bg2 = "#24283b",
	red0 = "#8c4351",
	red1 = "#f7768e",
	blue0 = "#3e5380",
	blue1 = "#6a92f7",
	blue2 = "#7dd3fc",
	green0 = "#618041",
	green1 = "#9ece6a",
	green2 = "#96ff96",
	teal = "#4fd6be",
	orange = "#ff966c",
	yellow0 = "#ffc777",
	yellow1 = "#ffff96",
	purple = "#bb9af7",
	grey = "#565f89",
	black = "#000000",
	none = "NONE",
}

vim.api.nvim_set_hl(0, "Normal", { fg = colors.fg, bg = colors.none })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = colors.fg, bg = colors.bg0 })
vim.api.nvim_set_hl(0, "FloatBorder", { link = "NormalFloat" })
vim.api.nvim_set_hl(0, "Terminal", { fg = colors.fg, bg = colors.none })
vim.api.nvim_set_hl(0, "EndOfBuffer", { fg = colors.bg0, bg = colors.none })
vim.api.nvim_set_hl(0, "Folded", { fg = colors.none, bg = colors.bg1 })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = colors.none })
vim.api.nvim_set_hl(0, "SignColumn", { fg = colors.fg, bg = colors.none })
vim.api.nvim_set_hl(0, "ToolbarLine", { fg = colors.fg, bg = colors.none })
vim.api.nvim_set_hl(0, "ColorColumn", { fg = colors.none, bg = colors.bg1 })
vim.api.nvim_set_hl(0, "Conceal", { fg = colors.grey, bg = colors.none })
vim.api.nvim_set_hl(0, "Cursor", { fg = colors.none, bg = colors.none })
vim.api.nvim_set_hl(0, "vCursor", { link = "Cursor" })
vim.api.nvim_set_hl(0, "iCursor", { link = "Cursor" })
vim.api.nvim_set_hl(0, "lCursor", { link = "Cursor" })
vim.api.nvim_set_hl(0, "CursorIM", { link = "Cursor" })
vim.api.nvim_set_hl(0, "CursorColumn", { fg = colors.none, bg = colors.bg1 })
vim.api.nvim_set_hl(0, "CursorLine", { fg = colors.none, bg = colors.bg0 })
vim.api.nvim_set_hl(0, "LineNr", { fg = colors.grey, bg = colors.none })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = colors.orange, bg = colors.none, bold = true })
vim.api.nvim_set_hl(0, "DiffAdd", { fg = colors.none, bg = colors.green0 })
vim.api.nvim_set_hl(0, "DiffChange", { fg = colors.none, bg = colors.blue0 })
vim.api.nvim_set_hl(0, "DiffDelete", { fg = colors.none, bg = colors.red0 })
vim.api.nvim_set_hl(0, "DiffText", { fg = colors.grey, bg = colors.none })
vim.api.nvim_set_hl(0, "Directory", { fg = colors.green1, bg = colors.none })
vim.api.nvim_set_hl(0, "ErrorMsg", { fg = colors.red1, bg = colors.none })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = colors.yellow0, bg = colors.none })
vim.api.nvim_set_hl(0, "ModeMsg", { fg = colors.fg, bg = colors.none })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = colors.blue1, bg = colors.none })
vim.api.nvim_set_hl(0, "Search", { fg = colors.black, bg = colors.red1 })
vim.api.nvim_set_hl(0, "IncSearch", { fg = colors.black, bg = colors.green0 })
vim.api.nvim_set_hl(0, "CurSearch", { link = "IncSearch" })
vim.api.nvim_set_hl(0, "MatchParen", { fg = colors.none, bg = colors.bg2 })
vim.api.nvim_set_hl(0, "NonText", { fg = colors.grey, bg = colors.none })
vim.api.nvim_set_hl(0, "Whitespace", { fg = colors.grey, bg = colors.none })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = colors.grey, bg = colors.none })
vim.api.nvim_set_hl(0, "Pmenu", { fg = colors.fg, bg = colors.bg0 })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = colors.black, bg = colors.green2 })
vim.api.nvim_set_hl(0, "PmenuSbar", { fg = colors.none, bg = colors.bg1 })
vim.api.nvim_set_hl(0, "PmenuThumb", { fg = colors.none, bg = colors.bg2 })
vim.api.nvim_set_hl(0, "WildMenu", { fg = colors.black, bg = colors.red1 })
vim.api.nvim_set_hl(0, "Question", { fg = colors.yellow0, bg = colors.none })
vim.api.nvim_set_hl(0, "SpellBad", { fg = colors.red1, bg = colors.none, undercurl = true, sp = colors.red1 })
vim.api.nvim_set_hl(0, "SpellCap", { fg = colors.yellow0, bg = colors.none, undercurl = true, sp = colors.yellow0 })
vim.api.nvim_set_hl(0, "SpellLocal", { fg = colors.blue1, bg = colors.none, undercurl = true, sp = colors.blue1 })
vim.api.nvim_set_hl(0, "SpellRare", { fg = colors.purple, bg = colors.none, undercurl = true, sp = colors.purple })
vim.api.nvim_set_hl(0, "StatusLine", { fg = colors.fg, bg = colors.bg0 })
vim.api.nvim_set_hl(0, "StatusLineTerm", { link = "StatusLine" })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = colors.grey, bg = colors.bg0 })
vim.api.nvim_set_hl(0, "StatusLineTermNC", { link = "StatusLineNC" })
vim.api.nvim_set_hl(0, "TabLine", { fg = colors.fg, bg = colors.bg2 })
vim.api.nvim_set_hl(0, "TabLineFill", { fg = colors.none, bg = colors.none })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = colors.black, bg = colors.blue1 })
vim.api.nvim_set_hl(0, "VertSplit", { fg = colors.grey, bg = colors.none })
vim.api.nvim_set_hl(0, "Visual", { fg = colors.none, bg = colors.bg2 })
vim.api.nvim_set_hl(0, "VisualNOS", { fg = colors.none, bg = colors.bg2, underline = true })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = colors.grey, bold = true })
vim.api.nvim_set_hl(0, "QuickFixLine", { fg = colors.blue1, bg = colors.none, bold = true })
vim.api.nvim_set_hl(0, "Debug", { fg = colors.yellow0, bg = colors.none })
vim.api.nvim_set_hl(0, "debugPC", { fg = colors.black, bg = colors.green1 })
vim.api.nvim_set_hl(0, "debugBreakpoint", { fg = colors.black, bg = colors.red1 })
vim.api.nvim_set_hl(0, "ToolbarButton", { fg = colors.black, bg = colors.blue2 })
vim.api.nvim_set_hl(0, "Type", { fg = colors.blue1, bg = colors.none })
vim.api.nvim_set_hl(0, "Structure", { fg = colors.blue1, bg = colors.none })
vim.api.nvim_set_hl(0, "StorageClass", { fg = colors.blue1, bg = colors.none })
vim.api.nvim_set_hl(0, "Identifier", { fg = colors.orange, bg = colors.none })
vim.api.nvim_set_hl(0, "Constant", { fg = colors.orange, bg = colors.none })
vim.api.nvim_set_hl(0, "PreProc", { fg = colors.red1, bg = colors.none })
vim.api.nvim_set_hl(0, "PreCondit", { fg = colors.red1, bg = colors.none })
vim.api.nvim_set_hl(0, "Include", { fg = colors.red1, bg = colors.none })
vim.api.nvim_set_hl(0, "Keyword", { fg = colors.red1, bg = colors.none })
vim.api.nvim_set_hl(0, "Define", { fg = colors.red1, bg = colors.none })
vim.api.nvim_set_hl(0, "Typedef", { fg = colors.red1, bg = colors.none })
vim.api.nvim_set_hl(0, "Exception", { fg = colors.red1, bg = colors.none })
vim.api.nvim_set_hl(0, "Conditional", { fg = colors.red1, bg = colors.none })
vim.api.nvim_set_hl(0, "Repeat", { fg = colors.red1, bg = colors.none })
vim.api.nvim_set_hl(0, "Statement", { fg = colors.red1, bg = colors.none })
vim.api.nvim_set_hl(0, "Macro", { fg = colors.purple, bg = colors.none })
vim.api.nvim_set_hl(0, "Error", { fg = colors.red1, bg = colors.none })
vim.api.nvim_set_hl(0, "Label", { fg = colors.purple, bg = colors.none })
vim.api.nvim_set_hl(0, "Special", { fg = colors.purple, bg = colors.none })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = colors.purple, bg = colors.none })
vim.api.nvim_set_hl(0, "Boolean", { fg = colors.purple, bg = colors.none })
vim.api.nvim_set_hl(0, "String", { fg = colors.yellow0, bg = colors.none })
vim.api.nvim_set_hl(0, "Character", { fg = colors.yellow0, bg = colors.none })
vim.api.nvim_set_hl(0, "Number", { fg = colors.purple, bg = colors.none })
vim.api.nvim_set_hl(0, "Float", { fg = colors.purple, bg = colors.none })
vim.api.nvim_set_hl(0, "Function", { fg = colors.green1, bg = colors.none })
vim.api.nvim_set_hl(0, "Operator", { fg = colors.red1, bg = colors.none })
vim.api.nvim_set_hl(0, "Title", { fg = colors.blue1, bg = colors.none, bold = true })
vim.api.nvim_set_hl(0, "Tag", { fg = colors.orange, bg = colors.none })
vim.api.nvim_set_hl(0, "Delimiter", { fg = colors.fg, bg = colors.none })
vim.api.nvim_set_hl(0, "Comment", { fg = colors.grey, bg = colors.none, italic = true })
vim.api.nvim_set_hl(0, "SpecialComment", { link = "Comment" })
vim.api.nvim_set_hl(0, "Todo", { fg = colors.blue1, bg = colors.none, italic = true })
vim.api.nvim_set_hl(0, "Ignore", { fg = colors.grey, bg = colors.none })
vim.api.nvim_set_hl(0, "Added", { fg = colors.green1, bg = colors.none })
vim.api.nvim_set_hl(0, "Changed", { fg = colors.blue1, bg = colors.none })
vim.api.nvim_set_hl(0, "Removed", { fg = colors.red0, bg = colors.none })

vim.api.nvim_set_hl(0, "LspReferenceText", { bg = colors.blue0 })
vim.api.nvim_set_hl(0, "LspReferenceRead", { bg = colors.blue0 })
vim.api.nvim_set_hl(0, "LspReferenceWrite", { bg = colors.blue0 })
vim.api.nvim_set_hl(0, "LspCodeLens", { fg = colors.grey })
vim.api.nvim_set_hl(0, "ComplHint", { fg = colors.bg0 })

vim.api.nvim_set_hl(0, "DiagnosticError", { fg = colors.red1 })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = colors.yellow1 })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = colors.green2 })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = colors.blue2 })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", { fg = colors.red1, bg = colors.bg1 })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", { fg = colors.yellow1, bg = colors.bg1 })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", { fg = colors.green2, bg = colors.bg1 })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", { fg = colors.blue2, bg = colors.bg1 })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { undercurl = true, sp = colors.red1 })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = colors.yellow1 })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = colors.green2 })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { undercurl = true, sp = colors.blue2 })

vim.api.nvim_set_hl(0, "StatusLineNormal", { fg = colors.black, bg = colors.blue1, bold = true })
vim.api.nvim_set_hl(0, "StatusLineInsert", { fg = colors.black, bg = colors.yellow0, bold = true })
vim.api.nvim_set_hl(0, "StatusLineVisual", { fg = colors.black, bg = colors.purple, bold = true })
vim.api.nvim_set_hl(0, "StatusLineCommand", { fg = colors.black, bg = colors.green2, bold = true })
vim.api.nvim_set_hl(0, "StatusLineTerminal", { fg = colors.black, bg = colors.teal, bold = true })
vim.api.nvim_set_hl(0, "StatusLineReplace", { fg = colors.black, bg = colors.red1, bold = true })

vim.api.nvim_set_hl(0, "BreakPointRed", { ctermbg = 0, fg = colors.red1, bg = colors.bg1 })
vim.api.nvim_set_hl(0, "BreakPointBlue", { ctermbg = 0, fg = colors.blue2, bg = colors.bg1 })
vim.api.nvim_set_hl(0, "BreakPointGreen", { ctermbg = 0, fg = colors.green2, bg = colors.bg1 })
vim.api.nvim_set_hl(0, "BreakPointYellow", { ctermbg = 0, fg = colors.yellow1, bg = colors.bg1 })

vim.api.nvim_set_hl(0, "MarkdownH1", { fg = colors.blue1, bg = colors.bg1, bold = true })
vim.api.nvim_set_hl(0, "MarkdownH2", { fg = colors.green1, bg = colors.bg1, bold = true })
vim.api.nvim_set_hl(0, "MarkdownH3", { fg = colors.orange, bg = colors.bg1, bold = true })
vim.api.nvim_set_hl(0, "MarkdownH4", { fg = colors.purple, bg = colors.bg1, bold = true })
vim.api.nvim_set_hl(0, "MarkdownH5", { fg = colors.yellow0, bg = colors.bg1, bold = true })
vim.api.nvim_set_hl(0, "MarkdownH6", { fg = colors.teal, bg = colors.bg1, bold = true })
vim.api.nvim_set_hl(0, "MarkdownH1Bg", { fg = colors.blue1, bg = colors.bg1, bold = true })
vim.api.nvim_set_hl(0, "MarkdownH2Bg", { fg = colors.green1, bg = colors.bg1, bold = true })
vim.api.nvim_set_hl(0, "MarkdownH3Bg", { fg = colors.orange, bg = colors.bg1, bold = true })
vim.api.nvim_set_hl(0, "MarkdownH4Bg", { fg = colors.purple, bg = colors.bg1, bold = true })
vim.api.nvim_set_hl(0, "MarkdownH5Bg", { fg = colors.yellow0, bg = colors.bg1, bold = true })
vim.api.nvim_set_hl(0, "MarkdownH6Bg", { fg = colors.teal, bg = colors.bg1, bold = true })

vim.api.nvim_set_hl(0, "MiniIconsAzure", { fg = colors.blue2 })
vim.api.nvim_set_hl(0, "MiniIconsBlue", { fg = colors.blue1 })
vim.api.nvim_set_hl(0, "MiniIconsCyan", { fg = colors.teal })
vim.api.nvim_set_hl(0, "MiniIconsGreen", { fg = colors.green2 })
vim.api.nvim_set_hl(0, "MiniIconsGrey", { fg = colors.grey })
vim.api.nvim_set_hl(0, "MiniIconsOrange", { fg = colors.orange })
vim.api.nvim_set_hl(0, "MiniIconsPurple", { fg = colors.purple })
vim.api.nvim_set_hl(0, "MiniIconsRed", { fg = colors.red1 })
vim.api.nvim_set_hl(0, "MiniIconsYellow", { fg = colors.yellow1 })

vim.api.nvim_set_hl(0, "NvimTreeFolderIcon", { fg = colors.grey })

vim.api.nvim_set_hl(0, "@variable", { fg = colors.fg, bg = colors.none })
