# created by eselect-repo

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[librewolf]
location = /var/db/repos/librewolf
sync-type = git
sync-uri = https://codeberg.org/librewolf/gentoo.git

[another-brave-overlay]
location = /var/db/repos/another-brave-overlay
sync-type = git
sync-uri = https://github.com/falbrechtskirchinger/another-brave-overlay.git
